### ISSUE TITLE
End location must be greater than or equal to start location 

### ISSUE THREAD

**Issue by feardley** [yachielab/SPADE#4]
Hi,
I have successfully run SPADE using the example dataset and a few other genomes. However when I run it on my genome of interest I get the following error:

C02Z412WL40Y:SPADE fne21$ SPADE.py -in SVEN.gbk
('Error in make_se_sets_all. dir', 'NZ_CP018074.1', 'prot_7884864_7885389')
local variable 'consensus_motif' referenced before assignment
Traceback (most recent call last):
  File "/Users/fne21/Bioinformatics/SPADE/SPADE.py", line 1209, in <module>
    spade.run(args.num_threads,[args.t, args.Nk, args.Nw, args.Ng, args.Ns, args.Np, args.Nu, args.Nm, args.Nr, args.Nq, args.Pk, args.Pw, args.Pg, args.Ps, args.Pp, args.Pu, args.Pm, args.Pr, args.Pq, args.v, args.delete, args.mafft, args.blastn, args.blastp])
  File "/Users/fne21/Bioinformatics/SPADE/SPADE.py", line 83, in run
    locus.all()
  File "/Users/fne21/Bioinformatics/SPADE/SPADE.py", line 434, in all
    self.make_feature_all()
  File "/Users/fne21/Bioinformatics/SPADE/SPADE.py", line 360, in make_feature_all
    feats = hra.make_feature()
  File "/Users/fne21/Bioinformatics/SPADE/SPADE.py", line 1076, in make_feature
    locations.append(FeatureLocation(part[0], part[-1]))  
  File "/usr/local/lib/python2.7/site-packages/Bio/SeqFeature.py", line 761, in __init__
    self.start))
ValueError: End location (5897952) must be greater than or equal to start location (5897962)
62)

Would you be able to shed some light on what this error means? As I am in the dark.

I have included the Genbank file for my organism below.

Thanks in advance,
Frank
[Terminal_Output.txt](https://github.com/yachielab/SPADE/files/3945914/Terminal_Output.txt)
[SVEN.gbk.txt](https://github.com/yachielab/SPADE/files/3945917/SVEN.gbk.txt)

**Comment by ponnhide** [comment]
I'm sorry for the late reply.
I fixed the problem you mentioned and pushed to Github. 
If you still face some problems, let me know.

**Comment by feardley** [comment]
Hi, Thank you for your help
I no longer receive the error message but the output folders still do not contain a repeat .gbk file or a _SPADE.gb file.
