### ISSUE TITLE
how to assemble a summary from multiple output folders?

### ISSUE THREAD

**Issue by l-yampolsky** [yachielab/SPADE#7]
I am trying to use SPADE to detect repeats in a draft genome assembly. (There are lots and lots of repeats there). SPADE installs and runs without a problem, thank you very much for making it available. However, my problem is that my draft assembly consists of thousands of contigs and so I am getting thousands of folders with results. My goal is to estimate portion of the genome in low complexity regions and the distribution of repeats lengths.

Would you advise me on how to achieve this from the output SPADE creates?

If I concatenate the contigs into one bumber-to-bumper input sequence, SPADE completes successfully, but produces only the _kmer_count.txt file and nothing else, so something must be wrong on my end.

I understand I can get annotations by get_spade_annotation.py, but if I run, in example folder this command

get_spade_annotation.py NC*/NC*_SPADE.gb

I get an empty SPADE_annotations.tsv file, which contains only the headers and nothing else.

Any advise on how I should proceed will be very much appreciated.

**Comment by l-yampolsky** [comment]
Let me ask the same question in a different way. If I do

grep 'period=\|rpt_num=' ./contig*/*_SPADE.gb > repeatsLandN.txt

- am I getting what I need?

(the question why execution of SPADE on one huge input sequence produces no output is still open).

**Comment by ponnhide** [comment]
I'm sorry that the description of the "README" is maybe not clear.  The "get_spade_annotation.py"  should be executed in the directory containing the target GenBank object. 

By the way, I couldn't estimate the reason why SPADE return no output for the concatenated huge input sequence. If you have an example input file that reproduces the problem, could you share it with me?
